// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discord_guild_settings.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteGuildSettings = `-- name: DeleteGuildSettings :exec
DELETE FROM discord_guild_settings WHERE guild_id = $1
`

func (q *Queries) DeleteGuildSettings(ctx context.Context, guildID string) error {
	_, err := q.db.Exec(ctx, deleteGuildSettings, guildID)
	return err
}

const getGuildSettings = `-- name: GetGuildSettings :one
SELECT id, guild_id, report_channel_id, channel_name, set_by_user_id, created_at, updated_at FROM discord_guild_settings WHERE guild_id = $1 LIMIT 1
`

func (q *Queries) GetGuildSettings(ctx context.Context, guildID string) (DiscordGuildSetting, error) {
	row := q.db.QueryRow(ctx, getGuildSettings, guildID)
	var i DiscordGuildSetting
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.ReportChannelID,
		&i.ChannelName,
		&i.SetByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConfiguredGuildIDs = `-- name: ListConfiguredGuildIDs :many
SELECT guild_id FROM discord_guild_settings
`

func (q *Queries) ListConfiguredGuildIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listConfiguredGuildIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var guild_id string
		if err := rows.Scan(&guild_id); err != nil {
			return nil, err
		}
		items = append(items, guild_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGuildSettings = `-- name: UpsertGuildSettings :one
INSERT INTO discord_guild_settings (id, guild_id, report_channel_id, channel_name, set_by_user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
ON CONFLICT (guild_id) DO UPDATE
    SET report_channel_id = EXCLUDED.report_channel_id,
        channel_name      = EXCLUDED.channel_name,
        set_by_user_id    = EXCLUDED.set_by_user_id,
        updated_at        = NOW()
RETURNING id, guild_id, report_channel_id, channel_name, set_by_user_id, created_at, updated_at
`

type UpsertGuildSettingsParams struct {
	ID              uuid.UUID `json:"id"`
	GuildID         string    `json:"guild_id"`
	ReportChannelID string    `json:"report_channel_id"`
	ChannelName     string    `json:"channel_name"`
	SetByUserID     string    `json:"set_by_user_id"`
}

func (q *Queries) UpsertGuildSettings(ctx context.Context, arg UpsertGuildSettingsParams) (DiscordGuildSetting, error) {
	row := q.db.QueryRow(ctx, upsertGuildSettings,
		arg.ID,
		arg.GuildID,
		arg.ReportChannelID,
		arg.ChannelName,
		arg.SetByUserID,
	)
	var i DiscordGuildSetting
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.ReportChannelID,
		&i.ChannelName,
		&i.SetByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
