// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountDiscordRegistrationsByGuild(ctx context.Context, guildID string) (int64, error)
	CountRecentVerificationCodesByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteDiscordRegistration(ctx context.Context, arg DeleteDiscordRegistrationParams) error
	DeleteExpiredRefreshTokens(ctx context.Context) (int64, error)
	DeleteGuildSettings(ctx context.Context, guildID string) error
	DeleteOAuthIdentity(ctx context.Context, id uuid.UUID) error
	DeleteStaleVerificationCodes(ctx context.Context) (int64, error)
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	GetDiscordGuildByGuildID(ctx context.Context, guildID string) (DiscordGuild, error)
	GetDiscordRegistration(ctx context.Context, arg GetDiscordRegistrationParams) (DiscordRegistration, error)
	GetGuildSettings(ctx context.Context, guildID string) (DiscordGuildSetting, error)
	GetOAuthIdentityByProviderUserID(ctx context.Context, arg GetOAuthIdentityByProviderUserIDParams) (OauthIdentity, error)
	GetOAuthIdentityByUserAndProvider(ctx context.Context, arg GetOAuthIdentityByUserAndProviderParams) (OauthIdentity, error)
	GetOAuthTokenByIdentity(ctx context.Context, oauthIdentityID uuid.UUID) (OauthToken, error)
	GetOldestRecentVerificationCode(ctx context.Context, userID uuid.UUID) (pgtype.Timestamptz, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetVerificationCodeByTokenHash(ctx context.Context, tokenHash string) (EmailVerificationCode, error)
	InsertEmailVerificationCode(ctx context.Context, arg InsertEmailVerificationCodeParams) (EmailVerificationCode, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error)
	LinkDiscordRegistrationToUser(ctx context.Context, arg LinkDiscordRegistrationToUserParams) error
	ListActiveRefreshTokensByUserID(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error)
	ListConfiguredGuildIDs(ctx context.Context) ([]string, error)
	ListDiscordGuilds(ctx context.Context) ([]DiscordGuild, error)
	ListDiscordRegistrationsByUser(ctx context.Context, userID pgtype.UUID) ([]DiscordRegistration, error)
	ListOAuthIdentitiesByUser(ctx context.Context, userID uuid.UUID) ([]OauthIdentity, error)
	MarkVerificationCodeUsed(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	SetEmailVerified(ctx context.Context, id uuid.UUID) error
	SetSetupProgress(ctx context.Context, arg SetSetupProgressParams) error
	UpdateRefreshTokenLastUsed(ctx context.Context, arg UpdateRefreshTokenLastUsedParams) error
	UpsertDiscordGuild(ctx context.Context, arg UpsertDiscordGuildParams) (DiscordGuild, error)
	UpsertDiscordRegistration(ctx context.Context, arg UpsertDiscordRegistrationParams) (DiscordRegistration, error)
	UpsertGuildSettings(ctx context.Context, arg UpsertGuildSettingsParams) (DiscordGuildSetting, error)
	UpsertOAuthToken(ctx context.Context, arg UpsertOAuthTokenParams) (OauthToken, error)
}

var _ Querier = (*Queries)(nil)
